package exception_handling_concept_try_catch;

public class Test {
 public static void main(String[] args) {
 
  int arr[] = new int[5];
  
  System.out.println("Hello Guys");
  
  try {
	  System.out.println(arr[8]);
} catch (Exception e) {
	// TODO: handle exception
}
   
   System.out.println("By guys");
  
	 
	 
	}
}
